### PR TITLE
Added missing output for private_route_table

### PR DESCRIPTION
**Pull request by rafzei**

### CODE REVIEW

**Review by plirglo — DISMISSED** [review]

**Review by mkyc — CHANGES_REQUESTED** [review]
Could you add section in Readme describing module output? That would be awesome!

**Comment by rafzei** [comment]
> Could you add section in Readme describing module output? That would be awesome!

@mkyc please take a look.

**Review by mkyc — APPROVED** [review]
LGTM

**Review by atsikham — APPROVED** [review]
LGTM

**Pull request merged**
